CREATE database IF NOT EXISTS Esparta_teste_pt2;

CREATE TABLE IF NOT EXISTS ALUNO (
    id INT AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS ALUNO_TURMA (
    aluno_id INT AUTO_INCREMENT,
    turma_id VARCHAR(45) NOT NULL,
    PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS DISCIPLINA (
    id INT AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS PROFESSOR (
    id INT AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS TURMA (
    id INT AUTO_INCREMENT,
    dia_da_semana INT NOT NULL,
    horario VARCHAR(45) NOT NULL,
    DISCIPLINA_id INT NOT NULL,
    PROFESSOR_id INT NOT NULL,
    ALUNO_id INT NOT NULL,
    PRIMARY KEY(id));

